### PR TITLE
IntelliJ 2023

### PR DESCRIPTION
**Pull request by mrexodia**
The changes are unfortunately quite large, but I had to resynchronize from the https://github.com/JetBrains/intellij-platform-plugin-template because a few things were broken with newer JDK/Kotlin/Gradle versions. I built successfully with JDK 21 and the latest IntelliJ.

### CODE REVIEW

**Comment by garyttierney** [comment]
LGTM. Thank you very much for putting in the effort to get upgraded to 2023.

**Review by garyttierney — APPROVED** [review]

**Comment by garyttierney** [comment]
FWIW, the publishing flow is currently broken (for an unrelated reason, it seems). I'll ping you here when it's fixed and your changes are live on the plugin marketplace.

**Comment by lightspot21** [comment]
Do we know if publishing is fixed? Having to maintain plugins across IntelliJ installs is quite annoying lately. If it's not on JetBrains's side I could try my hand at a PR, if that makes it easier.

**Comment by garyttierney** [comment]
Hey, sorry for the delay. The issue should be fixed now, and was just some new configuration on the JetBrains plugin site.

**Comment by garyttierney** [comment]
Latest version is now published on JetBrains marketplace. Sorry again for the delay.

**Pull request merged**
